theme:
    name: material
    features:
        - navigation.sections  # Sections are included in the navigation on the left.
        - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
        - header.autohide  # header disappears as you scroll
    palette:
        # Light mode / dark mode
        # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
        # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
        - scheme: default
          primary: white
          accent: amber
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: black
          accent: amber
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
    icon:
        repo: fontawesome/brands/github  # GitHub logo in top right
    logo: assets/logo.png
    favicon: assets/logo.png

site_name: evosax
site_description: The documentation for the evosax software library.

repo_url: https://github.com/RobertTLange/evosax
repo_name: RobertTLange/evosax
edit_uri: ""

strict: true  # Don't allow warnings during the build process

markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "Â¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4  # Prevents h5, h6 (i.e. methods) from showing up in the TOC.

extra_css:
    - assets/custom.css

plugins:
    - search:
        separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
    - ipynb
    - hippogriffe:
        extra_public_objects:
            - numpy.ndarray
            - jax.Array
            - jax.tree_util.Partial
            - jax.ShapeDtypeStruct
            - optax._src.base.GradientTransformation
            - flax.linen.module.Module
            - flax.core.scope.Scope
            - flax.linen.module._Sentinel
            - evosax.algorithms.base.State
            - evosax.algorithms.base.Params
            - evosax.algorithms.distribution_based.base.State
            - evosax.algorithms.distribution_based.base.Params
            - evosax.algorithms.population_based.base.State
            - evosax.algorithms.population_based.base.Params
            - evosax.problems.bbob.bbob.State
            - evosax.problems.bbob.meta_bbob.State
            - evosax.problems.bbob.meta_bbob.Params
            - evosax.problems.rl.gymnax.State
            - evosax.problems.rl.brax.State
            - evosax.problems.vision.torchvision.State
            - lineax.AbstractLinearSolver
            - lineax.AutoLinearSolver
            - optimistix.AbstractRootFinder
            - optimistix.Chord
    - mkdocstrings:
        handlers:
            python:
                options:
                    force_inspection: true
                    heading_level: 4
                    inherited_members: true
                    members_order: source
                    filters:
                        - "!^_[^_]"
                        - "!^__[^_]+__$"
                        - "^__init__$"
                    show_bases: false
                    show_if_no_docstring: true
                    show_overloads: false
                    show_root_heading: true
                    show_signature_annotations: true
                    show_source: false
                    show_symbol_type_heading: true
                    show_symbol_type_toc: true

nav:
    - Home: index.md
    - Getting Started: getting-started.md
    - Guides:
        - Ask-Eval-Tell Workflow: guides/ask-eval-tell.md
    - Examples:
        - Getting Started: 'examples/00_getting_started.ipynb'
        - Blackbox Optimization Benchmarking Problem: 'examples/01_bbob.ipynb'
        - Reinforcement Learning - Evolving MLP: 'examples/02_rl.ipynb'
        - Vision - Evolving CNN: 'examples/03_vision.ipynb'
        - Restart Evolution Strategy: 'examples/04_restart_es.ipynb'
        - Diffusion Evolution: 'examples/05_diffusion_evolution.ipynb'
        - Stein Variational Evolution Strategy: 'examples/06_sv_es.ipynb'
        - Persistent ES on Learning Rate Tuning Problem: 'examples/07_persistent_es.ipynb'
        - Evolution Strategy with Parallelization: 'examples/08_parallelization.ipynb'
    - Algorithms:
        - Distribution-based Strategies: algorithms/distribution.md
        - Population-based Strategies: algorithms/population.md
    - API Reference:
        - Algorithms: api/algorithms.md
        - Core Utilities: api/core.md
        - Learned Evolution: api/learned_evolution.md
        - Problem Suites: api/problems.md
        - Types: api/types.md
